New tables - OBS-14
ahoraquesinosven/api-registro-femicidios pull request #2
Opened 2023-12-04 23:18 UTC by Agus-Coder

Related to https://observatorioaqsnv.atlassian.net/browse/OBS-14

2023-12-05 01:52 UTC, andres-arana reviewed
@Agus-Coder te dejo unos comentarios menores para que los tengas en cuenta.

2023-12-05 01:52 UTC, andres-arana commented on migrations/20231202002710_new_tables.mjs
> +  table.string('victim_name_lastname', 50);
Cuidado con estos límites. Son de esas cosas que parecen lógicas hasta que viene alguien con un apellido compuesto gigante y el sistema explota porque no entra en la DB. En otra época tenía más sentido para controlar costos de storage, hoy en día el costo es negligible. Tenes más documentación [acá](https://www.postgresql.org/docs/current/datatype-character.html).

La mayoría de los campos que pusiste como `string('xyz', N)` yo los pondría como `table.specificType('xyz`, 'character varying');` Docs de por qué [acá](https://github.com/knex/knex/issues/4409).

Los únicos campos que dejaría con un límite son los que estás absolutamente seguro de que el límite es ese que pusiste. Ejemplo de esto sería la nacionalidad. Si vas a guardar el código ISO3 de la nacionalidad, sólo van a ser 3 caracteres. Pero ojo con esto porque cosas como `agressor_gender` no tenés un standard sobre el que apoyarte para asegurarte que realmente con 3 caracteres te alcanza. En general, defaultea a sin límites excepto los que puedas justificar que con un limitado alcanza.

2023-12-05 01:52 UTC, andres-arana commented on migrations/20231202002710_new_tables.mjs
> + knex.schema.withSchema('public').createTable('Victims', (table) => {
en general se usa para todos los nombres de tablas, campos y otras yerbas [snake case](https://en.wikipedia.org/wiki/Snake_case).

2023-12-14 02:29 UTC, andres-arana requested changes

2023-12-14 02:29 UTC, andres-arana commented on migrations/20231202002710_new_tables.mjs
> +  table.date('victim_last_update');
`xyz_creation` y `xyz_last_update` deberían ser NOT NULL

2023-12-14 02:29 UTC, andres-arana commented on migrations/20231202002710_new_tables.mjs
> +  table.text('victim_ocupation');
Esto debería ser un character varying

2023-12-14 02:29 UTC, andres-arana commented on migrations/20231202002710_new_tables.mjs
> +  table.boolean('victim_children');
Qué representa este flag?

2023-12-14 02:29 UTC, andres-arana commented on migrations/20231202002710_new_tables.mjs
> +  table.date('aggresor_last_update');
Lo mismo que antes, deberían ser NOT NULL

2023-12-14 02:29 UTC, andres-arana commented on migrations/20231202002710_new_tables.mjs
> +  table.boolean('aggresor_captive_history');
No termino de entender qué guardan estos campos

2023-12-14 02:29 UTC, andres-arana commented on migrations/20231202002710_new_tables.mjs
> +  table.boolean('aggresor_behaviour_post_case');
Por qué es un flag esto?

2023-12-14 02:29 UTC, andres-arana commented on migrations/20231202002710_new_tables.mjs
> +  table.date('last_update');
Deberían ser NOT NULL. Rompiste la convención acá, estás poniendo `case_campo` en todos lados excepto en `last_update` e `incident_date`.

2023-12-14 02:29 UTC, andres-arana commented on migrations/20231202002710_new_tables.mjs
> +  table.specificType('case_geographic_ubication', 'character varying');
Spanglish, es más común ponerle `location` más que `ubication` a las cosas. No me termina de quedar claro cuál es la diferencia entre este campo y el anterior.

2023-12-14 02:29 UTC, andres-arana commented on migrations/20231202002710_new_tables.mjs
> + knex.schema.withSchema('public').createTable('bonds', (table) => {
hmmm, bond me suena a instrumento financiero. Es más común hablar de relationship que de bond.

2023-12-14 02:29 UTC, andres-arana commented on migrations/20231202002710_new_tables.mjs
> +  table.date('child_last_update');
Lo mismo que en otros lugares, NOT NULL

2023-12-27 15:41 UTC, Agus-Coder commented
Cambios agregados

2025-05-10 18:12 UTC, closed without merging